<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <RootNamespace>PrintQueueApp.WinUI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Platforms>x64</Platforms>
    <Version>1.2.0-preview.1</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.3.1" />
  </ItemGroup>

  <Target Name="CopyAppResourcesToPublishDirectory" AfterTargets="Publish">
    <Copy SourceFiles="$(TargetDir)$(AssemblyName).pri"
          DestinationFiles="$(PublishDir)resources.pri"
          Condition="Exists('$(TargetDir)$(AssemblyName).pri')" />
    <ItemGroup>
      <AppXbf Include="$(IntermediateOutputPath)*.xbf" />
    </ItemGroup>
    <Copy SourceFiles="@(AppXbf)"
          DestinationFolder="$(PublishDir)"
          SkipUnchangedFiles="true" />
  </Target>
</Project>
